name: diagram
version: 0.1.0.0
github: "githubuser/diagram"
license: BSD3
author: "Gianluca Sant"
maintainer: "example@example.com"
copyright: "2020 Gianluca Sant"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/diagram#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - flow >= 1.0.19
  - parser-combinators == 1.2.1
  - parsec == 3.1.14.0
  - mtl == 2.2.2
  - extra >= 1.6.19
  - vector == 0.12.1.2
  - utility-ht >= 0.0.14
  - directory == 1.3.6.0
  - filepath == 1.4.2.1
  - bytestring == 0.10.10.0
  - binary == 0.8.7.0
  - text == 1.2.4.0
  - IfElse

library:
  source-dirs:
    - src/Font
    - src/Intermediate
    - src/IntermediateToAbs
    - src/Print
    - src/Svg
    - src/Parser
    - src/Check

default-extensions:
  - RecordWildCards
  - DuplicateRecordFields
  - MultiParamTypeClasses
  - FlexibleInstances
  - FunctionalDependencies
  - TupleSections
  - TypeFamilies
  - RecursiveDo
  - FlexibleContexts
  - PostfixOperators

executables:
  diagram-exe:
    main: Main.hs
    source-dirs:
      - app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -no-keep-hi-files
      - -no-keep-o-files
    dependencies:
      - diagram
